version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

jobs:
  plan:
    docker:
      - image: hashicorp/terraform:1.6.6
    steps:
      - checkout
      - run:
          name: Terragrunt Plan All
          command: |
            apt-get update && apt-get install -y unzip curl
            curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.17/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt
            pwd
            cd infra/environments/develop
            terragrunt run-all plan

  apply:
    docker:
      - image: hashicorp/terraform:1.6.6
    steps:
      - checkout
      - run:
          name: Terragrunt Apply All
          command: |
            apt-get update && apt-get install -y unzip curl
            curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.17/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt
            pwd
            cd infra/environments/develop
            terragrunt run-all apply --terragrunt-non-interactive

workflows:
  version: 2
  deploy:
    jobs:
      - plan
      - hold-apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold-apply
