version: 2.1

jobs:
  plan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Terragrunt
          command: |
            sudo apt-get update && sudo apt-get install -y curl unzip
            curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.17/terragrunt_linux_amd64 -o terragrunt
            chmod +x terragrunt
            sudo mv terragrunt /usr/local/bin/terragrunt
      - run:
          name: Terragrunt Plan All
          command: |
            pwd
            cd infra/environments/develop
            terragrunt run-all plan

  apply:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Terragrunt
          command: |
            sudo apt-get update && sudo apt-get install -y curl unzip
            curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.17/terragrunt_linux_amd64 -o terragrunt
            chmod +x terragrunt
            sudo mv terragrunt /usr/local/bin/terragrunt
      - run:
          name: Terragrunt Apply All
          command: |
            pwd
            cd infra/environments/develop
            terragrunt run-all apply --terragrunt-non-interactive

workflows:
  version: 2
  deploy:
    jobs:
      - plan
      - hold-apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold-apply
